const rows = [
 ['nassfutterautomaten','Nassfutterautomaten','both','Nassfutter Futterautomat Kühlung','Für planbare Nassfutter-Mahlzeiten zählen Kühlung, Fächergröße und Reinigung. Prüfe, wie lange das konkrete Futter unter deinen Raumbedingungen im Gerät bleiben darf.',['Kühlakkus oder aktive Kühlung und Herstellerangaben zur Nutzungsdauer prüfen.','Fachvolumen mit der tatsächlichen Portion vergleichen.','Entnehmbare Schalen und Reinigung nach jeder Befüllung einplanen.']],
 ['chip-futterautomaten','Chip- und RFID-Futterautomaten','both','Futterautomat Mikrochip RFID Haustier','Wenn Tiere unterschiedliches Futter bekommen, kann eine Zugangskontrolle helfen. Ein Chip-Napf ist nicht automatisch auch ein zeitgesteuerter Portionierer.',['Implantierten Mikrochip und Halsbandanhänger nicht gleichsetzen: Kompatibilität prüfen.','Prüfen, ob sich der Deckel auch bei einem zweiten Tier sicher schließt.','Napfform, Anlernphase und Batterien berücksichtigen.']],
 ['trinkbrunnen-katze','Edelstahl-Trinkbrunnen für Katzen','cat','Trinkbrunnen Katze Edelstahl','Entscheidend sind gut erreichbare Trinkflächen und eine Konstruktion, die sich regelmäßig vollständig reinigen lässt. Edelstahl im Namen sagt nichts über das Material aller Bauteile aus.',['Wasserkontaktflächen, Pumpe und Schläuche auf Zugänglichkeit prüfen.','Mindestfüllstand und Verhalten bei Stromausfall berücksichtigen.','Passende Filter samt Modellnummer und Folgekosten prüfen.']],
 ['trinkbrunnen-hund','Edelstahl-Trinkbrunnen für Hunde','dog','Trinkbrunnen Hund Edelstahl','Wasservolumen und Trinkhöhe müssen zur Größe deines Hundes passen. Ein hoher Tankinhalt ersetzt keinen regelmäßigen Wasserwechsel.',['Standfestigkeit und Größe der Trinkfläche prüfen.','Material sämtlicher wasserführender Teile kontrollieren.','Pumpe, Reinigung und Ersatzfilter vor dem Kauf vergleichen.']],
 ['gps-hund','GPS-Tracker für Hunde','dog','GPS Tracker Hund','Für Spaziergänge und Freilauf sind Netzabdeckung, sichere Befestigung und das Gewicht entscheidend. GPS-Ortung und Bluetooth-Suchhilfen sind unterschiedliche Systeme.',['Mobilfunkabdeckung im tatsächlichen Einsatzgebiet prüfen.','Abo, Mindestlaufzeit und Gesamtkosten vergleichen.','Aktualisierungsintervall und Akkulaufzeit im Live-Modus prüfen.']],
 ['gps-katze','GPS-Tracker für Katzen','cat','GPS Tracker Katze','Bei Katzen verdienen Gewicht und eine geeignete Halsbandlösung besondere Aufmerksamkeit. Prüfe die Größen- und Gewichtsempfehlung des konkreten Herstellers.',['Trackergewicht einschließlich Befestigung vergleichen.','Sicherheitsverschluss und Sitz des Halsbands prüfen.','Netzabdeckung, Abo und Ladehäufigkeit berücksichtigen.']],
 ['tierkameras','Tierkameras','both','Haustierkamera Hund Katze','Eine Kamera kann einen Blick nach Hause ermöglichen. Sie ersetzt keine Betreuung; Speicherort, Zugriffsschutz und abschaltbare Aufnahme gehören zur Kaufentscheidung.',['Bildwinkel und Aufstellort passend zum Raum wählen.','Lokale Speicherung, Cloud-Kosten und Löschmöglichkeiten prüfen.','Zwei-Faktor-Anmeldung und verfügbare Sicherheitsupdates prüfen.']],
 ['katzenklo-roboter','Katzenklo-Roboter','cat','Katzenklo selbstreinigend','Automatische Reinigung muss zu Größe, Gewicht und Verhalten deiner Katze passen. Maßgeblich sind die Sicherheits- und Nutzungsvorgaben des konkreten Modells.',['Mindestgewicht und Altersgrenzen des Herstellers beachten.','Innenraum, Einstieg und geeignete Streu prüfen.','Erkennung, Stoppfunktion und manuelle Reinigung vergleichen.']],
 ['mikrochip-katzenklappen','Mikrochip-Katzenklappen','cat','Mikrochip Katzenklappe','Chip-Kompatibilität und Einbaumaße entscheiden darüber, ob eine Klappe passt. Selektiver Zugang bedeutet nicht bei jedem Modell auch individuell steuerbaren Ausgang.',['Chipstandard und Anzahl speicherbarer Tiere prüfen.','Tür-, Wand- oder Glaseinbau einschließlich Adapter planen.','Durchgangsmaß, Batteriewarnung und Verriegelung vergleichen.']],
 ['fellpflege','Fellpflege-Systeme','dog','Fellpflege Staubsauger Hund','Aufsätze und Geräusch müssen zum Fell und zur Gewöhnung deines Hundes passen. Eine niedrig regelbare Stufe erleichtert einen vorsichtigen Einstieg.',['Eignung der Aufsätze für den Felltyp prüfen.','Regelbare Saugkraft und Geräuschangaben vergleichen.','Behälter, Schlauch und verfügbare Ersatzteile berücksichtigen.']],
 ['ballwerfer','Automatische Ballwerfer','dog','Automatischer Ballwerfer Hund','Ballwerfer sind Geräte für beaufsichtigtes Spiel. Passende Ballgröße, ein freier Wurfbereich und Pausen sind wichtiger als maximale Reichweite.',['Ballgröße passend zum Hund und ohne Verschluckrisiko wählen.','Kleinste Wurfdistanz und freien Sicherheitsbereich prüfen.','Pausen, Stromversorgung und Reinigung einplanen.']],
 ['ersatzfilter','Ersatzfilter für Trinkbrunnen','both','Trinkbrunnen Ersatzfilter Katze Hund','Filter sind modellspezifisches Zubehör. Vergleiche die genaue Gerätebezeichnung und die Abmessungen, bevor du ein Set bestellst.',['Modellnummer statt nur Markenname abgleichen.','Packungsinhalt und Preis pro Filter vergleichen.','Wechselintervall und Einweich- oder Spülhinweise des Herstellers beachten.']]
];
module.exports = rows.map(([id,title,pet,keywords,intro,criteria])=>({id,title,pet,keywords,intro,criteria}));
